[package]
name = "advent-of-code-2025"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc-runner = "*"
aoc-runner-derive = "*"
regex = "1.12.2"
rustc-hash = "2.1.1"

[profile.release]
lto = "fat"
overflow-checks = true
debug-assertions = true
